name: GitHub Trending Repositories

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 0 点运行一次，相当于北京时间 8 点
  workflow_dispatch:  # 手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pandas

    - name: Run Python script
      env:
        SCKEY: ${{ secrets.SCKEY }}  # 从 GitHub Secrets 中获取 SCKEY
        LANGUAGE: ${{ secrets.LANGUAGE }}  # 从 GitHub Secrets 中获取语言类型
      run: |
        python [爬取github热门项目.py](http://_vscodecontentref_/#%7B%22uri%22%3A%7B%22%24mid%22%3A1%2C%22fsPath%22%3A%22c%3A%5C%5CUsers%5C%5C123%5C%5CDesktop%5C%5Cpython%5C%5C%E7%88%AC%E5%8F%96github%E7%83%AD%E9%97%A8%E9%A1%B9%E7%9B%AE.py%22%2C%22_sep%22%3A1%2C%22path%22%3A%22%2Fc%3A%2FUsers%2F123%2FDesktop%2Fpython%2F%E7%88%AC%E5%8F%96github%E7%83%AD%E9%97%A8%E9%A1%B9%E7%9B%AE.py%22%2C%22scheme%22%3A%22file%22%7D%7D)
